### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by NinoSoles** [lovvskillz/python-discord-webhook#12]
I see no documentation for emoji support, is it possible to be added?

**Comment by RHQ-Rusty** [comment]
> I see no documentation for emoji support, is it possible to be added?

@NinoSoles It's entirely possible. Since the content that is getting sent is going into Discord channels, etc., once can safely expect that inputting ": joy :" (without the spaces, of course)somewhere into the content of a message will result in a 😂 being seen once the webhook has been executed.

Example:
```
whurl = url
whcontent = "Hello : joy :"
webhook = DiscordWebhook(url=whurl, content=whcontent)
webhoox.execute()
```
